engines:
  structure:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        go:
          mass_threshold: 30
exclude_patterns:
  - "**/*_test.go"
  - "**/*_tests.go"
  - "vendor/"
